name: Update SVG Stats

on:
  schedule:
    - cron: '0 */2 * * *'  # Runs every 2 hours (00:00, 02:00, 04:00, etc.)
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-svg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install requests python-dateutil

      - name: Run Python Script
        run: python update_svg.py  # This updates both SVG and README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add dark_mode.svg light_mode.svg README.md
          git commit -m "Updated SVG and README timestamp"
          git push
